name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    if: ${{ always() }}
    runs-on: big
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      RUSTFLAGS: "-C debuginfo=0"
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: restore cargo cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            target
          key: cargo-${{ runner.os }}-stable-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-stable-

      - name: run tests
        run: cargo test

      - name: publish netbox-openapi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p netbox-openapi

      - name: publish netbox
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p netbox
