name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: big
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      RUSTFLAGS: "-C debuginfo=0"
      CARGO_TARGET_DIR: target/ci
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: doc build
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
          CARGO_PROFILE_DEV_DEBUG: 0
        run: cargo doc --workspace --all-features --no-deps

      - name: run tests
        run: cargo test

      - name: publish netbox-openapi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p netbox-openapi

      - name: publish netbox
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p netbox

      - name: publish netbox-cli
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p netbox-cli
